<Project>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
    <LangVersion>14.0</LangVersion>
  </PropertyGroup>
  <Import Project="Directory.Build.local.props" Condition="Exists('Directory.Build.local.props')" />
</Project>
