FROM golang:1.24.8-alpine3.22 AS build
RUN GOBIN=/out CGO_ENABLED=0 go install github.com/minio/minio@RELEASE.2025-10-15T17-29-55Z

FROM alpine:3.22
RUN apk add --no-cache ca-certificates curl && \
    addgroup -S -g 1000 minio && \
    adduser -S -D -H -u 1000 -G minio minio && \
    install -d -o minio -g minio /data
COPY --from=build /out/minio /usr/local/bin/minio
USER minio
VOLUME ["/data"]
EXPOSE 9000 9001
ENTRYPOINT ["/usr/local/bin/minio"]
